### ISSUE TITLE
polygon check

### ISSUE THREAD

**Issue by hoesman** [eyza-cod2/zpam3#8] opened 2021-02-05 01:44 UTC
The polygons check is wrong as seen in picture, says needs to be -1 to 16, or -1 to 4 but complains when on -1, also why forcing sc_enable 0? Shadows forced off? That is pretty stupid
![great](https://user-images.githubusercontent.com/6295531/106978178-03014880-675c-11eb-8132-5ebec98a8bf5.jpg)

**Comment by eyza-cod2** [comment] 2021-03-16 17:21
There is a bug when the cvar is set to -1

I will fix this issue in next release.

Thanks for feedback

**Comment by hoesman** [comment] 2021-03-18 00:30
Also for some reason the mod is using almost triple the amount of ram than for example the beta 1
Example from linux
![Screenshot_1](https://user-images.githubusercontent.com/6295531/111555629-1820bc80-8789-11eb-9d68-b97e7f84b9da.png)

**Comment by eyza-cod2** [comment] 2021-03-18 10:19
In order to implement new features i had completly rewrite the codebase for this mod. It implements more object-oriented functions to make programming more easly and maintable, but for cost of more memory usage.

I think in these days its not a big problem to have more memory usage.

So thats not a bug, but a feature

**Comment by eyza-cod2** [comment] 2021-05-06 20:27
Fixed in 3.20

**Closed as completed by eyza-cod2** 2021-05-06 20:27 UTC

**Comment by hoesman** [comment] 2021-05-07 20:50
Polygon check yes, forcing shadows off not, whose brilliant idea is that?
